{
  auto r = ROOT::RDF::MakeCsvDataFrame("Book1.csv");
  //auto r1 = r.Range(0, 7);
  auto s1 = r.Graph("Ecm", "WWZL");
  //auto r2 = r.Range(8, 14);
  auto s2 = r.Graph("Ecm", "ZZZ");
  auto s3 = r.Graph("Ecm", "WWA");
  auto s4 = r.Graph("Ecm", "ZZ");
  auto s5 = r.Graph("Ecm", "DM");
  auto s6 = r.Graph("Ecm", "ZZAL");
  s1->SetLineColor(kYellow);
  s1->SetMarkerStyle(2);
  s1->SetLineWidth(3);
  s1->SetName("s1");
  s2->SetLineColor(kBlue);
  s2->SetMarkerStyle(2);
  s2->SetLineWidth(3);
  s2->SetName("s2");
  s3->SetLineColor(kViolet);
  s3->SetMarkerStyle(2);
  s3->SetLineWidth(3);
  s3->SetName("s3");
  s4->SetLineColor(kRed);
  s4->SetMarkerStyle(2);
  s4->SetLineWidth(3);
  s4->SetName("s4");
  s5->SetLineColor(kGreen);
  s5->SetMarkerStyle(2);
  s5->SetLineWidth(3);
  s5->SetName("s5");
  s6->SetLineColor(kGray);
  s6->SetMarkerStyle(2);
  s6->SetLineWidth(3);
  s6->SetName("s6");
  TCanvas c1;
  c1.SetLogy(1);
  s1->GetHistogram()->SetMaximum(0.1);
  s1->GetHistogram()->SetMinimum(0.000000001); 
  s1->SetTitle("Center of Mass Energy vs Cross Section");
  s1->GetXaxis()->SetTitle("E_{CM} [TeV]");
  s1->GetYaxis()->SetTitle("#sigma[pb]");
  s1->Draw("APL");
  s2->Draw("PL SAME");
  s3->Draw("PL SAME");
  s4->Draw("PL SAME");
  s5->Draw("PL SAME");
  s6->Draw("PL SAME");
  TLegend *l = new TLegend(0.55, 0.7, 0.9, 0.9);
  l->AddEntry("s1", "wwz :mu+ mu- > w+ w- z, w+ > l+ vl, w- > l- vl~, z > vl vl~", "l");
  l->AddEntry("s2", "zzz :mu+ mu- > z z z, z > l+ l-, z > vl vl~, z > vl vl~", "l");
  l->AddEntry("s3", "ww#gamma :mu+ mu- > w+ w- a, w+ > l+ vl, w- > l- vl~", "l");
  l->AddEntry("s4", "zz :mu+ mu- > z z, z > l+ l-, z > vl vl~", "l");
  l->AddEntry("s5", "#chi#chiz :mu+ mu- > chin chin~ z, z > l+ l-", "l");
  l->AddEntry("s6", "zz#gamma :mu+ mu- > z z a, z > l+ l-, z > vl vl~", "l");
  l->Draw();
}